#! /usr/bin/env python

'''
Manage configurations
'''

import sys
from os.path import expanduser
from argparse import ArgumentParser, ArgumentDefaultsHelpFormatter
import logging

import functions

def applyconf(args):
    '''
    Apply configuration
    '''
            
    functions.__muppet__['_dryrun'] = args.dryrun
    functions.__muppet__['_verbose'] = args.verbose
    functions.__muppet__['_directory'] = args.directory

    execfile(expanduser(args.directory) + '/index.py',
             functions.__muppet__.copy())

def main():
    '''
    Entry function
    '''

    parser = ArgumentParser(description="manage configurations")
    subs = parser.add_subparsers()
    papply = subs.add_parser('apply', help="apply configuration",
                             formatter_class=ArgumentDefaultsHelpFormatter)
    papply.add_argument('-d', '--directory', help="configuration directory",
                        default='~/.muppet')
    papply.add_argument('--dryrun', '-n', action='store_true',
                        help="don't perform any change")
    papply.add_argument('--verbose', '-v', action='store_true',
                        help="be more verbose")
    papply.set_defaults(func=applyconf)
    args = parser.parse_args()

    level = logging.DEBUG if args.verbose else logging.INFO
    logging.basicConfig(level=level, format="%(message)s")

    try:
        args.func(args)
    except IOError, exc:
        logging.error(exc)

if __name__ == '__main__':
    sys.exit(main())
